// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 The Fletcher Authors
//
#include "csharp_backend_visitor.hpp"

#include <sstream>
#include <string>
#include <variant>

#include "cpp_backend_schema_visitor.hpp"
#include "csharp_backend_type_table.hpp"
#include "generator_internal.hpp"
#include "type_mapper.hpp"

namespace fletcher::csharp_backend {

namespace {

using google::protobuf::Descriptor;
using google::protobuf::EnumDescriptor;
using ir::IrNode;
using ir::NodeKind;

// The kind a not-yet-generated field is reported as. Composite and temporal
// fields are BIND-6c's; naming them in the output keeps the slice boundary
// visible instead of dropping data silently.
const char* PendingKind(const IrNode& node) {
    switch (node.kind) {
        case NodeKind::LIST:
        case NodeKind::FIXED_SIZE_LIST:
            return "list";
        case NodeKind::STRUCT:
            return "struct";
        case NodeKind::MAP:
            return "map";
        case NodeKind::SCALAR:
            return "temporal";
        case NodeKind::UNSUPPORTED:
            return "unsupported";
    }
    return "unsupported";
}

// Every enum declared in `msg`, then in its nested messages, in declaration order.
void CollectEnums(const Descriptor* msg, std::vector<const EnumDescriptor*>& out) {
    for (int i = 0; i < msg->enum_type_count(); ++i) out.push_back(msg->enum_type(i));
    for (int i = 0; i < msg->nested_type_count(); ++i) CollectEnums(msg->nested_type(i), out);
}

}  // namespace

CsVisitor::CsVisitor(const google::protobuf::FileDescriptor* file) : file_(file) {}

std::string CsVisitor::GenerateEnum(const EnumDescriptor* enm) {
    std::ostringstream o;
    o << "public enum " << CsTypeName(enm) << " : int\n{\n";
    for (const auto& member : CsEnumMembers(enm))
        o << "    " << member.name << " = " << member.number << ",\n";
    o << "}\n";
    return o.str();
}

std::string CsVisitor::GenerateMessage(const Descriptor* msg) {
    std::ostringstream o;
    o << "public sealed class " << CsTypeName(msg) << "\n{\n";
    // The shared flatten walk, as TsVisitor uses it: field-level flatten inlining
    // and the unsupported-field drops are identical to the schema's field set.
    for (const auto& rec : cpp_backend::BuildFlattenedFieldList(msg)) {
        const IrNode& node = *rec.node;
        std::optional<CsScalarInfo> info;
        if (node.kind == NodeKind::SCALAR) {
            const auto& s = std::get<ir::ScalarNode>(node.node);
            info = CsLookupScalar(s.logical_type, s.enum_identity);
        }
        if (!info.has_value()) {
            o << "    // Not generated yet (BIND-6c): field '" << rec.name << "' ("
              << PendingKind(node) << ").\n";
            continue;
        }
        const bool nullable = node.facts.nullable;
        o << "    public " << info->type_text << (nullable ? "?" : "") << " "
          << CsPropertyName(rec.name, msg) << " { get; set; }";
        // A non-nullable reference starts as the proto default, never null, so the
        // property honours its own annotation.
        if (info->is_reference && !nullable)
            o << (info->type_text == "string" ? " = \"\";"
                                              : " = global::System.Array.Empty<byte>();");
        o << "\n";
    }
    o << "}\n";
    return o.str();
}

std::string CsVisitor::GenerateFile() {
    std::ostringstream o;
    // The <auto-generated> block is what Roslyn's analysers look for to skip a
    // file, as protoc's own C# output does. Without it a consumer building with
    // analysers as errors fails on our names by design (CA1707 on Outer_Inner and
    // Player_, CA1819 on byte[], CA1069 on enum aliases).
    o << "// <auto-generated>\n"
      << "//     Generated by fletcher-protoc. DO NOT EDIT.\n"
      << "//     Source: " << file_->name() << "\n"
      << "// </auto-generated>\n"
      << "#nullable enable\n\n"
      << "namespace " << CsNamespace(file_) << ";\n";

    std::vector<const EnumDescriptor*> enums;
    for (int i = 0; i < file_->enum_type_count(); ++i) enums.push_back(file_->enum_type(i));
    for (int i = 0; i < file_->message_type_count(); ++i)
        CollectEnums(file_->message_type(i), enums);
    for (const auto* enm : enums) o << "\n" << GenerateEnum(enm);

    for (const auto* msg : fletcher::OrderedMessages(file_)) {
        o << "\n";
        if (fletcher::IsRecursive(msg)) {
            o << "// Skipped: " << CsTypeName(msg) << " is recursive and cannot be represented.\n";
            continue;
        }
        o << GenerateMessage(msg);
    }
    return o.str();
}

}  // namespace fletcher::csharp_backend
