// <auto-generated>
//     Generated by fletcher-protoc. DO NOT EDIT.
//     Source: csharp_pair.proto
// </auto-generated>
#nullable enable

namespace Fletcher.Gen.Golden.Pair;

public enum Mood : int
{
    Unspecified = 0,
    Happy = 1,
}

public sealed class Stamp
{
    public string By { get; set; } = "";

    public static global::Apache.Arrow.Schema Schema { get; } = new global::Apache.Arrow.Schema(
        new global::Apache.Arrow.Field[]
        {
            new global::Apache.Arrow.Field("by", global::Apache.Arrow.Types.StringType.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }),
        },
        new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("proto_package", "golden.pair"), new("proto_message", "Stamp") });

    public static global::Apache.Arrow.RecordBatch ToArrow(global::System.Collections.Generic.IEnumerable<Stamp> rows)
    {
        global::System.ArgumentNullException.ThrowIfNull(rows);
        var all = rows as global::System.Collections.Generic.IReadOnlyList<Stamp> ?? new global::System.Collections.Generic.List<Stamp>(rows);
        return new global::Apache.Arrow.RecordBatch(Schema, ToArrowColumns(all), all.Count);
    }

    internal static global::Apache.Arrow.IArrowArray[] ToArrowColumns(global::System.Collections.Generic.IReadOnlyList<Stamp> rows)
    {
        var b0 = new global::Apache.Arrow.StringArray.Builder();
        foreach (var row in rows)
        {
            b0.Append(row.By);
        }
        var c0 = b0.Build();
        return new global::Apache.Arrow.IArrowArray[] { c0 };
    }

    public static Stamp FromArrow(global::Apache.Arrow.StructArray array, int index)
    {
        global::System.ArgumentNullException.ThrowIfNull(array);
        var row = new Stamp();
        row.By = ((global::Apache.Arrow.StringArray)array.Fields[0]).GetString(index) ?? "";
        return row;
    }
}

public sealed class Reading
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public double? Value { get; set; }
    public Mood Mood { get; set; }
    public global::System.Collections.Generic.List<int> Samples { get; set; } = new();
    public global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, long>> Tags { get; set; } = new();
    public Stamp? Stamp { get; set; }
    public global::System.Collections.Generic.List<Stamp> History { get; set; } = new();
    public global::Eiva.Fletcher.Model.Timestamp At { get; set; }

    public static global::Apache.Arrow.Schema Schema { get; } = new global::Apache.Arrow.Schema(
        new global::Apache.Arrow.Field[]
        {
            new global::Apache.Arrow.Field("id", global::Apache.Arrow.Types.Int32Type.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }),
            new global::Apache.Arrow.Field("name", global::Apache.Arrow.Types.StringType.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "2"), new("field_id", "2") }),
            new global::Apache.Arrow.Field("value", global::Apache.Arrow.Types.DoubleType.Default, true, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "3"), new("field_id", "3") }),
            new global::Apache.Arrow.Field("mood", global::Apache.Arrow.Types.Int32Type.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "4"), new("field_id", "4") }),
            new global::Apache.Arrow.Field("samples", new global::Apache.Arrow.Types.ListType(new global::Apache.Arrow.Field("item", global::Apache.Arrow.Types.Int32Type.Default, true)), false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "5"), new("field_id", "5") }),
            new global::Apache.Arrow.Field("tags", new global::Apache.Arrow.Types.MapType(new global::Apache.Arrow.Field("key", global::Apache.Arrow.Types.StringType.Default, false), new global::Apache.Arrow.Field("value", global::Apache.Arrow.Types.Int64Type.Default, true)), false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "6"), new("field_id", "6") }),
            new global::Apache.Arrow.Field("stamp", new global::Apache.Arrow.Types.StructType(new global::Apache.Arrow.Field[] { new global::Apache.Arrow.Field("by", global::Apache.Arrow.Types.StringType.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }) }), false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "7"), new("field_id", "7") }),
            new global::Apache.Arrow.Field("history", new global::Apache.Arrow.Types.ListType(new global::Apache.Arrow.Field("item", new global::Apache.Arrow.Types.StructType(new global::Apache.Arrow.Field[] { new global::Apache.Arrow.Field("by", global::Apache.Arrow.Types.StringType.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }) }), true, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("proto_package", "golden.pair"), new("proto_message", "Stamp") })), false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "8"), new("field_id", "8") }),
            new global::Apache.Arrow.Field("at", new global::Apache.Arrow.Types.TimestampType(global::Apache.Arrow.Types.TimeUnit.Nanosecond, (string?)null), false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "9"), new("field_id", "9") }),
        },
        new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("proto_package", "golden.pair"), new("proto_message", "Reading") });

    public static global::Apache.Arrow.RecordBatch ToArrow(global::System.Collections.Generic.IEnumerable<Reading> rows)
    {
        global::System.ArgumentNullException.ThrowIfNull(rows);
        var all = rows as global::System.Collections.Generic.IReadOnlyList<Reading> ?? new global::System.Collections.Generic.List<Reading>(rows);
        return new global::Apache.Arrow.RecordBatch(Schema, ToArrowColumns(all), all.Count);
    }

    internal static global::Apache.Arrow.IArrowArray[] ToArrowColumns(global::System.Collections.Generic.IReadOnlyList<Reading> rows)
    {
        var b0 = new global::Apache.Arrow.Int32Array.Builder();
        foreach (var row in rows)
        {
            b0.Append(row.Id);
        }
        var c0 = b0.Build();
        var b1 = new global::Apache.Arrow.StringArray.Builder();
        foreach (var row in rows)
        {
            b1.Append(row.Name);
        }
        var c1 = b1.Build();
        var b2 = new global::Apache.Arrow.DoubleArray.Builder();
        foreach (var row in rows)
        {
            if (row.Value is { } x2) b2.Append(x2); else b2.AppendNull();
        }
        var c2 = b2.Build();
        var b3 = new global::Apache.Arrow.Int32Array.Builder();
        foreach (var row in rows)
        {
            b3.Append((int)row.Mood);
        }
        var c3 = b3.Build();
        var t4 = (global::Apache.Arrow.Types.ListType)Schema.GetFieldByIndex(4).DataType;
        var o4 = new global::Apache.Arrow.ArrowBuffer.Builder<int>(rows.Count + 1);
        o4.Append(0);
        var b4 = new global::Apache.Arrow.Int32Array.Builder();
        foreach (var row in rows)
        {
            foreach (var x4 in row.Samples) b4.Append(x4);
            o4.Append(b4.Length);
        }
        var e4 = b4.Build();
        var c4 = new global::Apache.Arrow.ListArray(t4, rows.Count, o4.Build(), e4, global::Apache.Arrow.ArrowBuffer.Empty, 0, 0);
        var t5 = (global::Apache.Arrow.Types.MapType)Schema.GetFieldByIndex(5).DataType;
        var o5 = new global::Apache.Arrow.ArrowBuffer.Builder<int>(rows.Count + 1);
        o5.Append(0);
        var k5 = new global::Apache.Arrow.StringArray.Builder();
        var b5 = new global::Apache.Arrow.Int64Array.Builder();
        foreach (var row in rows)
        {
            foreach (var x5 in row.Tags)
            {
                k5.Append(x5.Key);
                b5.Append(x5.Value);
            }
            o5.Append(k5.Length);
        }
        var kv5 = new global::Apache.Arrow.StructArray(t5.KeyValueType, k5.Length, new global::Apache.Arrow.IArrowArray[] { k5.Build(), b5.Build() }, global::Apache.Arrow.ArrowBuffer.Empty, 0, 0);
        var c5 = new global::Apache.Arrow.MapArray(t5, rows.Count, o5.Build(), kv5, global::Apache.Arrow.ArrowBuffer.Empty, 0, 0);
        var t6 = (global::Apache.Arrow.Types.StructType)Schema.GetFieldByIndex(6).DataType;
        var r6 = new global::System.Collections.Generic.List<Stamp>(rows.Count);
        var m6 = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(rows.Count);
        foreach (var row in rows)
        {
            if (row.Stamp is { } x6) { r6.Add(x6); m6.Append(true); }
            else { r6.Add(new Stamp()); m6.Append(false); }
        }
        var z6 = m6.UnsetBitCount;
        var c6 = new global::Apache.Arrow.StructArray(t6, rows.Count, Stamp.ToArrowColumns(r6), z6 > 0 ? m6.Build() : global::Apache.Arrow.ArrowBuffer.Empty, z6, 0);
        var t7 = (global::Apache.Arrow.Types.ListType)Schema.GetFieldByIndex(7).DataType;
        var o7 = new global::Apache.Arrow.ArrowBuffer.Builder<int>(rows.Count + 1);
        o7.Append(0);
        var f7 = new global::System.Collections.Generic.List<Stamp>();
        foreach (var row in rows)
        {
            f7.AddRange(row.History);
            o7.Append(f7.Count);
        }
        var e7 = new global::Apache.Arrow.StructArray((global::Apache.Arrow.Types.StructType)t7.ValueDataType, f7.Count, Stamp.ToArrowColumns(f7), global::Apache.Arrow.ArrowBuffer.Empty, 0, 0);
        var c7 = new global::Apache.Arrow.ListArray(t7, rows.Count, o7.Build(), e7, global::Apache.Arrow.ArrowBuffer.Empty, 0, 0);
        var t8 = (global::Apache.Arrow.Types.TimestampType)Schema.GetFieldByIndex(8).DataType;
        var v8 = new global::Apache.Arrow.ArrowBuffer.Builder<long>(rows.Count);
        var m8 = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(rows.Count);
        foreach (var row in rows)
        {
            v8.Append(row.At.WithUnit(t8.Unit).Value);
            m8.Append(true);
        }
        var z8 = m8.UnsetBitCount;
        var c8 = new global::Apache.Arrow.TimestampArray(t8, v8.Build(), z8 > 0 ? m8.Build() : global::Apache.Arrow.ArrowBuffer.Empty, rows.Count, z8, 0);
        return new global::Apache.Arrow.IArrowArray[] { c0, c1, c2, c3, c4, c5, c6, c7, c8 };
    }

    public static Reading FromArrow(global::Apache.Arrow.StructArray array, int index)
    {
        global::System.ArgumentNullException.ThrowIfNull(array);
        var row = new Reading();
        row.Id = ((global::Apache.Arrow.Int32Array)array.Fields[0]).GetValue(index).GetValueOrDefault();
        row.Name = ((global::Apache.Arrow.StringArray)array.Fields[1]).GetString(index) ?? "";
        row.Value = ((global::Apache.Arrow.DoubleArray)array.Fields[2]).GetValue(index);
        row.Mood = (Mood)((global::Apache.Arrow.Int32Array)array.Fields[3]).GetValue(index).GetValueOrDefault();
        {
            var l = (global::Apache.Arrow.ListArray)array.Fields[4];
            var e = (global::Apache.Arrow.Int32Array)l.Values;
            var start = l.ValueOffsets[index];
            var end = l.ValueOffsets[index + 1];
            var x = new global::System.Collections.Generic.List<int>(end - start);
            for (var j = start; j < end; j++) x.Add(e.GetValue(j).GetValueOrDefault());
            row.Samples = x;
        }
        {
            var m = (global::Apache.Arrow.MapArray)array.Fields[5];
            var k = (global::Apache.Arrow.StringArray)m.Keys;
            var e = (global::Apache.Arrow.Int64Array)m.Values;
            var start = m.ValueOffsets[index];
            var end = m.ValueOffsets[index + 1];
            var x = new global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, long>>(end - start);
            for (var j = start; j < end; j++) x.Add(new global::System.Collections.Generic.KeyValuePair<string, long>(k.GetString(j) ?? "", e.GetValue(j).GetValueOrDefault()));
            row.Tags = x;
        }
        { var s = (global::Apache.Arrow.StructArray)array.Fields[6]; row.Stamp = s.IsNull(index) ? null : Stamp.FromArrow(s, index); }
        {
            var l = (global::Apache.Arrow.ListArray)array.Fields[7];
            var e = (global::Apache.Arrow.StructArray)l.Values;
            var start = l.ValueOffsets[index];
            var end = l.ValueOffsets[index + 1];
            var x = new global::System.Collections.Generic.List<Stamp>(end - start);
            for (var j = start; j < end; j++) x.Add(Stamp.FromArrow(e, j));
            row.History = x;
        }
        {
            var a = (global::Apache.Arrow.TimestampArray)array.Fields[8];
            var t = (global::Apache.Arrow.Types.TimestampType)a.Data.DataType;
            row.At = new global::Eiva.Fletcher.Model.Timestamp(a.GetValue(index).GetValueOrDefault(), t.Unit, t.Timezone);
        }
        return row;
    }
}

public sealed class Marks
{
    // Not generated yet (BIND-6e): field 'at' (list) has no C# type here.

    public static global::Apache.Arrow.Schema Schema { get; } = new global::Apache.Arrow.Schema(
        new global::Apache.Arrow.Field[]
        {
            new global::Apache.Arrow.Field("at", new global::Apache.Arrow.Types.ListType(new global::Apache.Arrow.Field("item", new global::Apache.Arrow.Types.StructType(new global::Apache.Arrow.Field[] { new global::Apache.Arrow.Field("seconds", global::Apache.Arrow.Types.Int64Type.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }), new global::Apache.Arrow.Field("nanos", global::Apache.Arrow.Types.Int32Type.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "2"), new("field_id", "2") }) }), true, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("proto_package", "google.protobuf"), new("proto_message", "Timestamp") })), false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }),
        },
        new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("proto_package", "golden.pair"), new("proto_message", "Marks") });

    // ToArrow and FromArrow are not generated: field 'at' is a message from another file (BIND-6e).
}

/// <summary>The topic of Telemetry.Report: the segments a C++ publisher of the same method uses.</summary>
public static class Telemetry_ReportTopic
{
    /// <summary>The topic's segments, the package being one segment with its dots kept.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<string> Segments { get; } = new[] { "golden.pair", "Telemetry", "Report" };

    /// <summary>The segments joined with '/'.</summary>
    public const string Key = "golden.pair/Telemetry/Report";
}

// Skipped: Telemetry.Ping — request is not streaming (pub/sub requires 'stream' on request)

/// <summary>The topic of Telemetry.Mark: the segments a C++ publisher of the same method uses.</summary>
public static class Telemetry_MarkTopic
{
    /// <summary>The topic's segments, the package being one segment with its dots kept.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<string> Segments { get; } = new[] { "golden.pair", "Telemetry", "Mark" };

    /// <summary>The segments joined with '/'.</summary>
    public const string Key = "golden.pair/Telemetry/Mark";
}
