// <auto-generated>
//     Generated by fletcher-protoc. DO NOT EDIT.
//     Source: csharp_pair.proto
// </auto-generated>
#nullable enable

namespace Fletcher.Gen.Golden.Pair;

/// <summary>Receives one <see cref="Reading"/> published on Telemetry.Report, with its attachments.</summary>
/// <param name="row">The decoded row; the handler owns it.</param>
/// <param name="attachments">BORROWED for this call only.</param>
public delegate void Telemetry_ReportHandler(Reading row, global::Eiva.Fletcher.AttachmentsView attachments);

/// <summary>Publishes <see cref="Reading"/> rows on Telemetry.Report, over one provider.</summary>
/// <remarks>
/// Declares the topic with <see cref="Reading.Schema"/> when constructed: the native
/// publish path accepts rows only on a topic THIS publisher declared. Not thread-safe to
/// dispose while publishing.
/// </remarks>
public sealed class Telemetry_ReportPublisher : global::System.IDisposable
{
    /// <summary>The topic, from <see cref="Telemetry_ReportTopic"/>.</summary>
    public static global::Eiva.Fletcher.TopicPath Topic { get; } = global::Eiva.Fletcher.TopicPath.Of([.. Telemetry_ReportTopic.Segments]);

    /// <summary>The topic's segments joined with '/'.</summary>
    public const string TopicKey = Telemetry_ReportTopic.Key;

    /// <summary>The schema rows travel under: <see cref="Reading.Schema"/>.</summary>
    public static global::Apache.Arrow.Schema Schema => Reading.Schema;

    private readonly global::Eiva.Fletcher.Publisher _publisher;
    private readonly global::Eiva.Fletcher.FletcherCodec _codec;

    /// <summary>Declares the topic on <paramref name="provider"/> with the row schema.</summary>
    /// <param name="provider">Borrowed; it must outlive this publisher.</param>
    /// <param name="options">The topic's options, or <see langword="null"/> for the provider's defaults.</param>
    public Telemetry_ReportPublisher(global::Eiva.Fletcher.PubSubProviderHandle provider, global::Eiva.Fletcher.TopicOptions? options = null)
    {
        global::System.ArgumentNullException.ThrowIfNull(provider);
        _codec = new global::Eiva.Fletcher.FletcherCodec(Reading.Schema);
        try
        {
            _publisher = new global::Eiva.Fletcher.Publisher(provider);
            try
            {
                _publisher.CreateTopic(Topic, Reading.Schema, options);
            }
            catch
            {
                _publisher.Dispose();
                throw;
            }
        }
        catch
        {
            _codec.Dispose();
            throw;
        }
    }

    /// <summary>Publishes one row, before returning.</summary>
    /// <remarks>
    /// Builds a one-row Arrow batch, binds it and publishes it. That is the costly shape: measured
    /// at about 3.8 microseconds a row, 19.6 times the generated C++ publisher, mostly in
    /// Apache.Arrow building and exporting the batch (c-abi/benchmarks/README.md, D-BIND-49).
    /// To publish many rows, prefer <c>Publish(IEnumerable&lt;Reading&gt;)</c>,
    /// which builds and binds once (about 1.23 times C++ per row).
    /// </remarks>
    public void Publish(Reading row) => Publish(row, null);

    /// <summary>Publishes one row with its attachments, before returning.</summary>
    /// <remarks>The cost is <see cref="Publish(Reading)"/>'s.</remarks>
    public void Publish(Reading row, global::Eiva.Fletcher.AttachmentsBuilder? attachments)
    {
        global::System.ArgumentNullException.ThrowIfNull(row);
        using var batch = Reading.ToArrow(new[] { row });
        using var bound = _codec.Bind(batch);
        _publisher.Publish(Topic, bound, 0, attachments);
    }

    /// <summary>Publishes every row, building and binding them once: the fast path.</summary>
    /// <remarks>A failure at row k leaves rows before it published: the runtime does not unwind a partial publication.</remarks>
    public void Publish(global::System.Collections.Generic.IEnumerable<Reading> rows)
    {
        global::System.ArgumentNullException.ThrowIfNull(rows);
        using var batch = Reading.ToArrow(rows);
        if (batch.Length == 0) return;
        using var bound = _codec.Bind(batch);
        _publisher.Publish(Topic, bound);
    }

    /// <summary>Releases the publisher and its codec.</summary>
    public void Dispose()
    {
        _publisher.Dispose();
        _codec.Dispose();
    }
}

/// <summary>Receives <see cref="Reading"/> rows published on Telemetry.Report, over one provider.</summary>
/// <remarks>
/// Each row is decoded with <see cref="Reading.Schema"/>, as C++'s generated subscriber decodes
/// with its own class. There is no <c>SubscribeInPlace</c> (Q16): for many rows, receive
/// batches with <c>Eiva.Fletcher.SubscriberArrow</c> and read them with <see cref="Reading.FromArrow"/>.
/// </remarks>
public sealed class Telemetry_ReportSubscriber : global::System.IDisposable
{
    /// <summary>The topic, from <see cref="Telemetry_ReportTopic"/>.</summary>
    public static global::Eiva.Fletcher.TopicPath Topic { get; } = global::Eiva.Fletcher.TopicPath.Of([.. Telemetry_ReportTopic.Segments]);

    /// <summary>The topic's segments joined with '/'.</summary>
    public const string TopicKey = Telemetry_ReportTopic.Key;

    /// <summary>The schema rows travel under: <see cref="Reading.Schema"/>.</summary>
    public static global::Apache.Arrow.Schema Schema => Reading.Schema;

    private readonly global::Eiva.Fletcher.Subscriber _subscriber;
    private readonly global::Eiva.Fletcher.FletcherCodec _codec;

    /// <summary>Binds to <paramref name="provider"/>; the topic is not declared here.</summary>
    /// <param name="provider">Borrowed; it must outlive this subscriber.</param>
    public Telemetry_ReportSubscriber(global::Eiva.Fletcher.PubSubProviderHandle provider)
    {
        global::System.ArgumentNullException.ThrowIfNull(provider);
        _codec = new global::Eiva.Fletcher.FletcherCodec(Reading.Schema);
        try
        {
            _subscriber = new global::Eiva.Fletcher.Subscriber(provider);
        }
        catch
        {
            _codec.Dispose();
            throw;
        }
    }

    /// <summary>Begins delivering rows to <paramref name="handler"/>; never blocks.</summary>
    /// <remarks>
    /// The handler runs on a transport thread with the row it owns and the attachments
    /// BORROWED for the call. An exception it throws is absorbed and raised as
    /// <see cref="HandlerFaulted"/>.
    /// </remarks>
    /// <param name="handler">Called once per row.</param>
    /// <param name="options">The topic's options, or <see langword="null"/> for the provider's defaults.</param>
    /// <returns>The subscription; dispose it or pass it to <see cref="Unsubscribe"/> to stop.</returns>
    public global::Eiva.Fletcher.Subscription Subscribe(Telemetry_ReportHandler handler, global::Eiva.Fletcher.TopicOptions? options = null)
    {
        global::System.ArgumentNullException.ThrowIfNull(handler);
        var codec = _codec;
        var result = _subscriber.Subscribe(Topic, (bytes, schema, attachments) =>
        {
            using var batch = codec.Decode(bytes);
            var columns = new global::Apache.Arrow.StructArray(
                new global::Apache.Arrow.Types.StructType(batch.Schema.FieldsList), batch.Length, batch.Arrays,
                global::Apache.Arrow.ArrowBuffer.Empty, 0);
            handler(Reading.FromArrow(columns, 0), attachments);
        }, options);
        result.Schema.Dispose();
        return result.Subscription;
    }

    /// <summary>Stops a subscription; no delivery begins after this returns.</summary>
    public void Unsubscribe(global::Eiva.Fletcher.Subscription subscription) => _subscriber.Unsubscribe(subscription);

    /// <summary>Raised when a handler throws; the exception does not reach the transport.</summary>
    public event global::System.EventHandler<global::Eiva.Fletcher.HandlerFaultedEventArgs>? HandlerFaulted
    {
        add => _subscriber.HandlerFaulted += value;
        remove => _subscriber.HandlerFaulted -= value;
    }

    /// <summary>How many handler exceptions have been absorbed.</summary>
    public ulong AbsorbedCallbackFailures => _subscriber.AbsorbedCallbackFailures;

    /// <summary>Releases the subscriber and its codec.</summary>
    public void Dispose()
    {
        _subscriber.Dispose();
        _codec.Dispose();
    }
}

// Skipped: Telemetry.Ping — request is not streaming (pub/sub requires 'stream' on request)

// Skipped: Telemetry.Mark — Marks has no ToArrow / FromArrow: field 'at' is a message from another file (BIND-6e).
