name: "Install VS2022 Build Tools (v143)"
description: Installs Visual Studio 2022 Build Tools (v143) and Windows 11 SDK.
runs:
  using: "composite"
  steps:
    - name: Install VS2022 Build Tools (v143)
      shell: cmd
      run: |
        curl -SL --output %TEMP%\vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe

        (start /w %TEMP%\vs_buildtools.exe --quiet --wait --norestart --nocache --installPath "C:\Program Files\Microsoft Visual Studio\2022\Professional" --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.ATLMFC --add Microsoft.VisualStudio.Component.Windows11SDK.22621 || IF "%ERRORLEVEL%"=="3010" EXIT 0)

        dir "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC"
        dir "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build"
