// Verifies that protoc-generated Encode() and arrow-bridge Codec.EncodeRow()
// produce byte-identical output for the same row content + schema. This is
// THE invariant that lets edge code (typed proto rows, no Apache Arrow C++)
// interoperate with server-side decoders that work in arrow::Schema/ArrowRow.

#include "telemetry.fletcher.pb.h" // generated by protoc-gen-fletcher

#include <arrow_bridge/codec.hpp>

#include <arrow/api.h>
#include <gtest/gtest.h>

#include <memory>
#include <vector>

using namespace fletcher;

namespace
{
    std::shared_ptr<arrow::Schema> TelemetrySchema()
    {
        return arrow::schema({
            arrow::field("sensor_id", arrow::int32()),
            arrow::field("temperature", arrow::float64()),
            arrow::field("label", arrow::utf8()),
            arrow::field("valid", arrow::boolean()),
            arrow::field("readings", arrow::list(arrow::int32())),
        });
    }

    ArrowRow MakeArrowRow(int32_t sensor_id,
                          double temperature,
                          const std::string &label,
                          bool valid,
                          const std::vector<int32_t> &readings)
    {
        arrow::Int32Builder list_builder;
        if (auto s = list_builder.AppendValues(readings); !s.ok()) {
            ADD_FAILURE() << s;
        }
        std::shared_ptr<arrow::Array> list_array;
        if (auto s = list_builder.Finish(&list_array); !s.ok()) {
            ADD_FAILURE() << s;
        }

        return ArrowRow{
            std::make_shared<arrow::Int32Scalar>(sensor_id),
            std::make_shared<arrow::DoubleScalar>(temperature),
            std::make_shared<arrow::StringScalar>(label),
            std::make_shared<arrow::BooleanScalar>(valid),
            std::make_shared<arrow::ListScalar>(list_array),
        };
    }

} // namespace

TEST(ProtocArrowBridgeByteCompat, GeneratedEncodeMatchesCodecEncode)
{
    fletcher_gen::integration::Telemetry generated;
    generated.set_sensor_id(42)
             .set_temperature(23.5)
             .set_label("intake")
             .set_valid(true)
             .set_readings({100, 200, 300});
    EncodedRow generated_bytes = generated.Encode();

    Codec codec(TelemetrySchema());
    EncodedRow codec_bytes = codec.EncodeRow(
        MakeArrowRow(42, 23.5, "intake", true, {100, 200, 300}));

    EXPECT_EQ(generated_bytes, codec_bytes)
        << "protoc-generated Encode() and arrow-bridge Codec.EncodeRow() "
           "produced different bytes for the same row + schema";
}

TEST(ProtocArrowBridgeByteCompat, GeneratedEncodingDecodesViaCodec)
{
    fletcher_gen::integration::Telemetry generated;
    generated.set_sensor_id(7)
             .set_temperature(-12.75)
             .set_label("")
             .set_valid(false)
             .set_readings({10, 20, 30});

    Codec codec(TelemetrySchema());
    EncodedRow generated_bytes = generated.Encode();
    ArrowRow decoded = codec.DecodeRow(generated_bytes);

    ASSERT_EQ(decoded.size(), 5u);
    EXPECT_EQ(std::static_pointer_cast<arrow::Int32Scalar>(decoded[0])->value, 7);
    EXPECT_EQ(std::static_pointer_cast<arrow::DoubleScalar>(decoded[1])->value, -12.75);
    EXPECT_EQ(std::static_pointer_cast<arrow::StringScalar>(decoded[2])->ToString(), "");
    EXPECT_EQ(std::static_pointer_cast<arrow::BooleanScalar>(decoded[3])->value, false);

    auto* readings = dynamic_cast<arrow::ListScalar*>(decoded[4].get());
    ASSERT_NE(readings, nullptr);
    ASSERT_EQ(readings->value->length(), 3);
    auto values = std::static_pointer_cast<arrow::Int32Array>(readings->value);
    EXPECT_EQ(values->Value(0), 10);
    EXPECT_EQ(values->Value(1), 20);
    EXPECT_EQ(values->Value(2), 30);
}

// Reverse direction of GeneratedEncodingDecodesViaCodec: bytes produced by
// arrow-bridge's Codec.EncodeRow() must be decodable by the protoc-generated
// row class via its EncodedRow constructor. Together with the forward test
// this proves bidirectional byte-compat.
TEST(ProtocArrowBridgeByteCompat, CodecEncodingDecodesViaGenerated)
{
    Codec codec(TelemetrySchema());
    EncodedRow codec_bytes = codec.EncodeRow(
        MakeArrowRow(99, 6.25, "cabin", true, {1, 2, 3}));

    fletcher_gen::integration::Telemetry decoded(codec_bytes);

    EXPECT_EQ(decoded.sensor_id(), 99);
    EXPECT_EQ(decoded.temperature(), 6.25);
    EXPECT_EQ(decoded.label(), "cabin");
    EXPECT_EQ(decoded.valid(), true);
    ASSERT_EQ(decoded.readings().size(), 3u);
    EXPECT_EQ(decoded.readings()[0], 1);
    EXPECT_EQ(decoded.readings()[1], 2);
    EXPECT_EQ(decoded.readings()[2], 3);
}
