// Verifies that protoc-generated Encode() and arrow-bridge Codec.EncodeRow()
// produce byte-identical output for the same row content + schema. This is
// THE invariant that lets edge code (typed proto rows, no Apache Arrow C++)
// interoperate with server-side decoders that work in arrow::Schema/ArrowRow.

#include "telemetry.fletcher.pb.h" // generated by protoc-gen-fletcher

#include <arrow_bridge/codec.hpp>

#include <arrow/api.h>
#include <gtest/gtest.h>

#include <memory>
#include <vector>

using namespace fletcher;

namespace
{
    std::shared_ptr<arrow::Schema> TelemetrySchema()
    {
        return arrow::schema({
            arrow::field("sensor_id", arrow::int32()),
            arrow::field("temperature", arrow::float64()),
            arrow::field("label", arrow::utf8()),
            arrow::field("valid", arrow::boolean()),
            arrow::field("readings", arrow::list(arrow::int32())),
        });
    }

    ArrowRow MakeArrowRow(int32_t sensor_id,
                          double temperature,
                          const std::string &label,
                          bool valid,
                          const std::vector<int32_t> &readings)
    {
        arrow::Int32Builder list_builder;
        if (auto s = list_builder.AppendValues(readings); !s.ok()) {
            ADD_FAILURE() << s;
        }
        std::shared_ptr<arrow::Array> list_array;
        if (auto s = list_builder.Finish(&list_array); !s.ok()) {
            ADD_FAILURE() << s;
        }

        return ArrowRow{
            std::make_shared<arrow::Int32Scalar>(sensor_id),
            std::make_shared<arrow::DoubleScalar>(temperature),
            std::make_shared<arrow::StringScalar>(label),
            std::make_shared<arrow::BooleanScalar>(valid),
            std::make_shared<arrow::ListScalar>(list_array),
        };
    }

} // namespace

TEST(ProtocArrowBridgeByteCompat, GeneratedEncodeMatchesCodecEncode)
{
    fletcher_gen::integration::Telemetry generated;
    generated.set_sensor_id(42)
             .set_temperature(23.5)
             .set_label("intake")
             .set_valid(true)
             .set_readings({100, 200, 300});
    EncodedRow generated_bytes = generated.Encode();

    Codec codec(TelemetrySchema());
    EncodedRow codec_bytes = codec.EncodeRow(
        MakeArrowRow(42, 23.5, "intake", true, {100, 200, 300}));

    EXPECT_EQ(generated_bytes, codec_bytes)
        << "protoc-generated Encode() and arrow-bridge Codec.EncodeRow() "
           "produced different bytes for the same row + schema";
}

TEST(ProtocArrowBridgeByteCompat, GeneratedEncodingDecodesViaCodec)
{
    fletcher_gen::integration::Telemetry generated;
    generated.set_sensor_id(7)
             .set_temperature(-12.75)
             .set_label("")
             .set_valid(false)
             .set_readings({0});

    Codec codec(TelemetrySchema());
    ArrowRow decoded = codec.DecodeRow(generated.Encode());

    ASSERT_EQ(decoded.size(), 5u);
    EXPECT_EQ(std::static_pointer_cast<arrow::Int32Scalar>(decoded[0])->value, 7);
    EXPECT_EQ(std::static_pointer_cast<arrow::DoubleScalar>(decoded[1])->value, -12.75);
    EXPECT_EQ(std::static_pointer_cast<arrow::StringScalar>(decoded[2])->ToString(), "");
    EXPECT_EQ(std::static_pointer_cast<arrow::BooleanScalar>(decoded[3])->value, false);
}
