// <auto-generated>
//     Generated by fletcher-protoc. DO NOT EDIT.
//     Source: google/protobuf/timestamp.proto
// </auto-generated>
#nullable enable

namespace Fletcher.Gen.Google.Protobuf;

public sealed class Timestamp
{
    public long Seconds { get; set; }
    public int Nanos { get; set; }

    public static global::Apache.Arrow.Schema Schema { get; } = new global::Apache.Arrow.Schema(
        new global::Apache.Arrow.Field[]
        {
            new global::Apache.Arrow.Field("seconds", global::Apache.Arrow.Types.Int64Type.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "1"), new("field_id", "1") }),
            new global::Apache.Arrow.Field("nanos", global::Apache.Arrow.Types.Int32Type.Default, false, new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("field_number", "2"), new("field_id", "2") }),
        },
        new global::System.Collections.Generic.KeyValuePair<string, string>[] { new("proto_package", "google.protobuf"), new("proto_message", "Timestamp") });

    public static global::Apache.Arrow.RecordBatch ToArrow(global::System.Collections.Generic.IEnumerable<Timestamp> rows)
    {
        global::System.ArgumentNullException.ThrowIfNull(rows);
        var all = rows as global::System.Collections.Generic.IReadOnlyList<Timestamp> ?? new global::System.Collections.Generic.List<Timestamp>(rows);
        return new global::Apache.Arrow.RecordBatch(Schema, ToArrowColumns(all), all.Count);
    }

    internal static global::Apache.Arrow.IArrowArray[] ToArrowColumns(global::System.Collections.Generic.IReadOnlyList<Timestamp> rows)
    {
        var b0 = new global::Apache.Arrow.Int64Array.Builder();
        foreach (var row in rows)
        {
            b0.Append(row.Seconds);
        }
        var c0 = b0.Build();
        var b1 = new global::Apache.Arrow.Int32Array.Builder();
        foreach (var row in rows)
        {
            b1.Append(row.Nanos);
        }
        var c1 = b1.Build();
        return new global::Apache.Arrow.IArrowArray[] { c0, c1 };
    }

    public static Timestamp FromArrow(global::Apache.Arrow.StructArray array, int index)
    {
        global::System.ArgumentNullException.ThrowIfNull(array);
        var row = new Timestamp();
        row.Seconds = ((global::Apache.Arrow.Int64Array)array.Fields[0]).GetValue(index).GetValueOrDefault();
        row.Nanos = ((global::Apache.Arrow.Int32Array)array.Fields[1]).GetValue(index).GetValueOrDefault();
        return row;
    }
}
