// Generated by fletcher-protoc. DO NOT EDIT.
// Source: coverage_scalar_nested.proto

import type { TypedSchema } from '@eiva/fletcher-gateway-client';
import { WireTypeId } from '@eiva/fletcher-gateway-client';

export interface IScalarListWrapper {
  values: number[];
}

export const ScalarListWrapper: TypedSchema<IScalarListWrapper> = {
  fields: [
    { name: 'values', fieldNumber: 1, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
  ],
  protoPackage: 'integration.coverage.scalar_nested',
  protoMessage: 'ScalarListWrapper',
};

export interface INestedScalarListWrapper {
  values: number[][];
}

export const NestedScalarListWrapper: TypedSchema<INestedScalarListWrapper> = {
  fields: [
    { name: 'values', fieldNumber: 1, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } } },
  ],
  protoPackage: 'integration.coverage.scalar_nested',
  protoMessage: 'NestedScalarListWrapper',
};

export interface IScalarNestedCoverage {
  flattened_scalar_list: number[];
  optional_flattened_scalar_list: number[] | null;
  nested_scalar_lists: number[][];
  depth3_scalar_lists: number[][][];
}

export const ScalarNestedCoverage: TypedSchema<IScalarNestedCoverage> = {
  fields: [
    { name: 'flattened_scalar_list', fieldNumber: 1, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
    { name: 'optional_flattened_scalar_list', fieldNumber: 3, wireType: WireTypeId.LIST, nullable: true, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
    { name: 'nested_scalar_lists', fieldNumber: 5, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } } },
    { name: 'depth3_scalar_lists', fieldNumber: 7, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } } } },
  ],
  protoPackage: 'integration.coverage.scalar_nested',
  protoMessage: 'ScalarNestedCoverage',
};

