// Generated by fletcher-protoc. DO NOT EDIT.
// Source: coverage.proto

import type { TypedSchema } from '@eiva/fletcher-gateway-client';
import { WireTypeId } from '@eiva/fletcher-gateway-client';

export interface INestedEnums {
  state: number;
}

export const NestedEnums: TypedSchema<INestedEnums> = {
  fields: [
    { name: 'state', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'NestedEnums',
};

export interface IScalarCoverage {
  bool_value: boolean;
  int32_value: number;
  int64_value: bigint;
  uint32_value: number;
  uint64_value: bigint;
  sint32_value: number;
  sint64_value: bigint;
  fixed32_value: number;
  fixed64_value: bigint;
  sfixed32_value: number;
  sfixed64_value: bigint;
  float_value: number;
  double_value: number;
  string_value: string;
  bytes_value: Uint8Array;
  optional_bool: boolean | null;
  optional_int32: number | null;
  optional_string: string | null;
  optional_bytes: Uint8Array | null;
  wrapped_bool: boolean | null;
  wrapped_int32: number | null;
  wrapped_int64: bigint | null;
  wrapped_uint32: number | null;
  wrapped_uint64: bigint | null;
  wrapped_float: number | null;
  wrapped_double: number | null;
  wrapped_string: string | null;
  wrapped_bytes: Uint8Array | null;
  timestamp_value: bigint;
  duration_value: bigint;
  status: number;
  nested_status: number;
}

export const ScalarCoverage: TypedSchema<IScalarCoverage> = {
  fields: [
    { name: 'bool_value', fieldNumber: 1, wireType: WireTypeId.BOOL, nullable: false },
    { name: 'int32_value', fieldNumber: 2, wireType: WireTypeId.INT32, nullable: false },
    { name: 'int64_value', fieldNumber: 3, wireType: WireTypeId.INT64, nullable: false },
    { name: 'uint32_value', fieldNumber: 4, wireType: WireTypeId.UINT32, nullable: false },
    { name: 'uint64_value', fieldNumber: 5, wireType: WireTypeId.UINT64, nullable: false },
    { name: 'sint32_value', fieldNumber: 6, wireType: WireTypeId.INT32, nullable: false },
    { name: 'sint64_value', fieldNumber: 7, wireType: WireTypeId.INT64, nullable: false },
    { name: 'fixed32_value', fieldNumber: 8, wireType: WireTypeId.UINT32, nullable: false },
    { name: 'fixed64_value', fieldNumber: 9, wireType: WireTypeId.UINT64, nullable: false },
    { name: 'sfixed32_value', fieldNumber: 10, wireType: WireTypeId.INT32, nullable: false },
    { name: 'sfixed64_value', fieldNumber: 11, wireType: WireTypeId.INT64, nullable: false },
    { name: 'float_value', fieldNumber: 12, wireType: WireTypeId.FLOAT32, nullable: false },
    { name: 'double_value', fieldNumber: 13, wireType: WireTypeId.FLOAT64, nullable: false },
    { name: 'string_value', fieldNumber: 14, wireType: WireTypeId.STRING, nullable: false },
    { name: 'bytes_value', fieldNumber: 15, wireType: WireTypeId.BINARY, nullable: false },
    { name: 'optional_bool', fieldNumber: 16, wireType: WireTypeId.BOOL, nullable: true },
    { name: 'optional_int32', fieldNumber: 17, wireType: WireTypeId.INT32, nullable: true },
    { name: 'optional_string', fieldNumber: 18, wireType: WireTypeId.STRING, nullable: true },
    { name: 'optional_bytes', fieldNumber: 19, wireType: WireTypeId.BINARY, nullable: true },
    { name: 'wrapped_bool', fieldNumber: 20, wireType: WireTypeId.BOOL, nullable: true },
    { name: 'wrapped_int32', fieldNumber: 21, wireType: WireTypeId.INT32, nullable: true },
    { name: 'wrapped_int64', fieldNumber: 22, wireType: WireTypeId.INT64, nullable: true },
    { name: 'wrapped_uint32', fieldNumber: 23, wireType: WireTypeId.UINT32, nullable: true },
    { name: 'wrapped_uint64', fieldNumber: 24, wireType: WireTypeId.UINT64, nullable: true },
    { name: 'wrapped_float', fieldNumber: 25, wireType: WireTypeId.FLOAT32, nullable: true },
    { name: 'wrapped_double', fieldNumber: 26, wireType: WireTypeId.FLOAT64, nullable: true },
    { name: 'wrapped_string', fieldNumber: 27, wireType: WireTypeId.STRING, nullable: true },
    { name: 'wrapped_bytes', fieldNumber: 28, wireType: WireTypeId.BINARY, nullable: true },
    { name: 'timestamp_value', fieldNumber: 29, wireType: WireTypeId.TIMESTAMP_NANO, nullable: false },
    { name: 'duration_value', fieldNumber: 30, wireType: WireTypeId.DURATION_NANO, nullable: false },
    { name: 'status', fieldNumber: 31, wireType: WireTypeId.INT32, nullable: false },
    { name: 'nested_status', fieldNumber: 32, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'ScalarCoverage',
};

export interface ILeaf {
  id: number;
  label: string;
  status: number;
}

export const Leaf: TypedSchema<ILeaf> = {
  fields: [
    { name: 'id', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
    { name: 'label', fieldNumber: 2, wireType: WireTypeId.STRING, nullable: false },
    { name: 'status', fieldNumber: 3, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'Leaf',
};

export interface IBranch {
  leaf: ILeaf;
  optional_leaf: ILeaf | null;
  leaves: ILeaf[];
}

export const Branch: TypedSchema<IBranch> = {
  fields: [
    { name: 'leaf', fieldNumber: 1, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields },
    { name: 'optional_leaf', fieldNumber: 2, wireType: WireTypeId.STRUCT, nullable: true, fields: Leaf.fields },
    { name: 'leaves', fieldNumber: 3, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'Branch',
};

export interface IStructListWrapper {
  values: ILeaf[];
}

export const StructListWrapper: TypedSchema<IStructListWrapper> = {
  fields: [
    { name: 'values', fieldNumber: 1, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'StructListWrapper',
};

export interface INestedStructListWrapper {
  values: ILeaf[][];
}

export const NestedStructListWrapper: TypedSchema<INestedStructListWrapper> = {
  fields: [
    { name: 'values', fieldNumber: 1, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } } },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'NestedStructListWrapper',
};

export interface IFlattenedPoint {
  x: number;
  y: number;
}

export const FlattenedPoint: TypedSchema<IFlattenedPoint> = {
  fields: [
    { name: 'x', fieldNumber: 1, wireType: WireTypeId.FLOAT64, nullable: false },
    { name: 'y', fieldNumber: 2, wireType: WireTypeId.FLOAT64, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'FlattenedPoint',
};

export interface IFieldFlattenedPosition {
  x: number;
  y: number;
}

export const FieldFlattenedPosition: TypedSchema<IFieldFlattenedPosition> = {
  fields: [
    { name: 'x', fieldNumber: 1, wireType: WireTypeId.FLOAT64, nullable: false },
    { name: 'y', fieldNumber: 2, wireType: WireTypeId.FLOAT64, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'FieldFlattenedPosition',
};

export interface ICompositeCoverage {
  scalars: IScalarCoverage;
  optional_scalars: IScalarCoverage | null;
  branch: IBranch;
  optional_branch: IBranch | null;
  repeated_scalar: number[];
  repeated_string: string[];
  repeated_bytes: Uint8Array[];
  repeated_struct: ILeaf[];
  map_scalar: Map<string, number>;
  map_struct: Map<string, ILeaf>;
  flattened_struct_list: IStructListWrapper[];
  nested_struct_lists: ILeaf[][];
  depth3_struct_lists: ILeaf[][][];
  optional_flattened_struct_list: IStructListWrapper[] | null;
  message_flattened_point: IFlattenedPoint;
  field_flattened_position: IFieldFlattenedPosition;
}

export const CompositeCoverage: TypedSchema<ICompositeCoverage> = {
  fields: [
    { name: 'scalars', fieldNumber: 1, wireType: WireTypeId.STRUCT, nullable: false, fields: ScalarCoverage.fields },
    { name: 'optional_scalars', fieldNumber: 2, wireType: WireTypeId.STRUCT, nullable: true, fields: ScalarCoverage.fields },
    { name: 'branch', fieldNumber: 3, wireType: WireTypeId.STRUCT, nullable: false, fields: Branch.fields },
    { name: 'optional_branch', fieldNumber: 4, wireType: WireTypeId.STRUCT, nullable: true, fields: Branch.fields },
    { name: 'repeated_scalar', fieldNumber: 5, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
    { name: 'repeated_string', fieldNumber: 6, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRING, nullable: false } },
    { name: 'repeated_bytes', fieldNumber: 7, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.BINARY, nullable: false } },
    { name: 'repeated_struct', fieldNumber: 8, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } },
    { name: 'map_scalar', fieldNumber: 9, wireType: WireTypeId.MAP, nullable: false, mapKey: { name: '', fieldNumber: 0, wireType: WireTypeId.STRING, nullable: false }, mapValue: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
    { name: 'map_struct', fieldNumber: 10, wireType: WireTypeId.MAP, nullable: false, mapKey: { name: '', fieldNumber: 0, wireType: WireTypeId.STRING, nullable: false }, mapValue: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } },
    { name: 'flattened_struct_list', fieldNumber: 12, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: StructListWrapper.fields } },
    { name: 'nested_struct_lists', fieldNumber: 14, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } } },
    { name: 'depth3_struct_lists', fieldNumber: 16, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: Leaf.fields } } } },
    { name: 'optional_flattened_struct_list', fieldNumber: 18, wireType: WireTypeId.LIST, nullable: true, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: StructListWrapper.fields } },
    { name: 'message_flattened_point', fieldNumber: 19, wireType: WireTypeId.STRUCT, nullable: false, fields: FlattenedPoint.fields },
    { name: 'field_flattened_position', fieldNumber: 20, wireType: WireTypeId.STRUCT, nullable: false, fields: FieldFlattenedPosition.fields },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'CompositeCoverage',
};

export interface IServiceRequest {
  payload: ICompositeCoverage;
}

export const ServiceRequest: TypedSchema<IServiceRequest> = {
  fields: [
    { name: 'payload', fieldNumber: 1, wireType: WireTypeId.STRUCT, nullable: false, fields: CompositeCoverage.fields },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'ServiceRequest',
};

export interface IServiceReply {
  accepted: boolean;
  message: string;
}

export const ServiceReply: TypedSchema<IServiceReply> = {
  fields: [
    { name: 'accepted', fieldNumber: 1, wireType: WireTypeId.BOOL, nullable: false },
    { name: 'message', fieldNumber: 2, wireType: WireTypeId.STRING, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'ServiceReply',
};

// Skipped: CoverageService.Submit — request is not streaming (pub/sub requires 'stream' on request)
