// Generated by fletcher-protoc. DO NOT EDIT.
// Source: enum_coverage.proto

import type { TypedSchema } from '@eiva/fletcher-gateway-client';
import { WireTypeId } from '@eiva/fletcher-gateway-client';

export interface IEnumOwner {
  marker: number;
}

export const EnumOwner: TypedSchema<IEnumOwner> = {
  fields: [
    { name: 'marker', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'EnumOwner',
};

export interface IEnumCoverage {
  status: number;
  nullable_status: number | null;
  statuses: number[];
  status_by_name: Map<string, number>;
  nested_status: number;
}

export const EnumCoverage: TypedSchema<IEnumCoverage> = {
  fields: [
    { name: 'status', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
    { name: 'nullable_status', fieldNumber: 2, wireType: WireTypeId.INT32, nullable: true },
    { name: 'statuses', fieldNumber: 3, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
    { name: 'status_by_name', fieldNumber: 4, wireType: WireTypeId.MAP, nullable: false, mapKey: { name: '', fieldNumber: 0, wireType: WireTypeId.STRING, nullable: false }, mapValue: { name: '', fieldNumber: 0, wireType: WireTypeId.INT32, nullable: false } },
    { name: 'nested_status', fieldNumber: 5, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'EnumCoverage',
};

export interface IFlattenedEnumOwner {
  wrapped_items: IEnumOwner[];
}

export const FlattenedEnumOwner: TypedSchema<IFlattenedEnumOwner> = {
  fields: [
    { name: 'wrapped_items', fieldNumber: 1, wireType: WireTypeId.LIST, nullable: false, element: { name: '', fieldNumber: 0, wireType: WireTypeId.STRUCT, nullable: false, fields: EnumOwner.fields } },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'FlattenedEnumOwner',
};

export interface IFlattenedEnumRef {
  wrapped: number;
}

export const FlattenedEnumRef: TypedSchema<IFlattenedEnumRef> = {
  fields: [
    { name: 'wrapped', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'FlattenedEnumRef',
};

export interface IRecursiveEnumRef {
  rec: number;
}

export const RecursiveEnumRef: TypedSchema<IRecursiveEnumRef> = {
  fields: [
    { name: 'rec', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'RecursiveEnumRef',
};

export interface IImportedEnumCarrier {
  carrier_status: number;
  carrier_amount: number;
}

export const ImportedEnumCarrier: TypedSchema<IImportedEnumCarrier> = {
  fields: [
    { name: 'carrier_status', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
    { name: 'carrier_amount', fieldNumber: 2, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'ImportedEnumCarrier',
};

export interface IFieldFlattenedEnum {
  carrier_status: number;
  carrier_amount: number;
}

export const FieldFlattenedEnum: TypedSchema<IFieldFlattenedEnum> = {
  fields: [
    { name: 'carrier_status', fieldNumber: 1, wireType: WireTypeId.INT32, nullable: false },
    { name: 'carrier_amount', fieldNumber: 2, wireType: WireTypeId.INT32, nullable: false },
  ],
  protoPackage: 'integration.coverage',
  protoMessage: 'FieldFlattenedEnum',
};

