// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 The Fletcher Authors
//
// GIR-5 forcing test: the unified schema visitor drives BOTH schema paths — the
// generated C++ <Class>Schema() source (CppSchemaSink) and the in-process / IPC
// ArrowSchema (NanoarrowSchemaSink) — and they agree.
//
// Two guarantees are checked per node-kind fixture:
//
//   1. .ipc byte identity: the schema built through the IR-driven nanoarrow sink
//      (BuildMessageSchemaIntoFromIr), serialized to Arrow IPC, is byte-identical
//      to a committed golden captured from today's pre-migration emitter. This is
//      the anti-drift guard; it is the red-first cutover signal (a stubbed visitor
//      mismatches the golden) and stays green once the visitor emits correctly.
//
//   2. one visitor, both sinks agree: running the SAME SchemaVisitor with the C++
//      source sink and with the nanoarrow sink issues an identical ordered stream
//      of sink operations (types, names, nullability, metadata, deep-copies). A
//      recording decorator wraps each real sink and the two op traces must match,
//      proving the source-render and direct-exec paths cannot diverge.
//
// The goldens are regenerated by running with FLETCHER_CAPTURE_GOLDENS=1 (which
// writes them from the legacy in-process BuildMessageSchema into SCHEMA_GOLDEN_DIR
// and then skips); normal runs read the committed files.

#include <google/protobuf/descriptor.h>
#include <google/protobuf/descriptor.pb.h>
#include <gtest/gtest.h>
#include <nanoarrow/nanoarrow.hpp>

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "cpp_backend_schema_visitor.hpp"
#include "schema_builder.hpp"

using namespace google::protobuf;
namespace cb = fletcher::cpp_backend;

namespace {

// ===========================================================================
// In-memory fixtures — one message per schema node-kind scenario. No custom
// options are needed (field-level flatten and nested lists are exercised by the
// protoc-coverage integration goldens); these cover the option-free kinds.
// ===========================================================================

FieldDescriptorProto* AddField(DescriptorProto* msg, const char* name, int number,
                               FieldDescriptorProto::Type type,
                               FieldDescriptorProto::Label label = FieldDescriptorProto::LABEL_OPTIONAL) {
    auto* f = msg->add_field();
    f->set_name(name);
    f->set_number(number);
    f->set_type(type);
    f->set_label(label);
    return f;
}

void AddMapEntry(DescriptorProto* owner, DescriptorProto* msg, const char* field_name,
                 int field_number, const char* entry_name, FieldDescriptorProto::Type key_type,
                 FieldDescriptorProto::Type value_type, const char* value_type_name = nullptr) {
    auto* entry = owner->add_nested_type();
    entry->set_name(entry_name);
    entry->mutable_options()->set_map_entry(true);
    AddField(entry, "key", 1, key_type);
    auto* vf = AddField(entry, "value", 2, value_type);
    if (value_type_name) vf->set_type_name(value_type_name);

    auto* f = AddField(msg, field_name, field_number, FieldDescriptorProto::TYPE_MESSAGE,
                       FieldDescriptorProto::LABEL_REPEATED);
    f->set_type_name(entry_name);
}

// Owns the descriptor pool + all fixture messages for the whole test run.
class Fixtures {
public:
    Fixtures() {
        BuildWkt();
        BuildProto2();
        BuildMain();
    }

    const Descriptor* Get(const std::string& name) const {
        const Descriptor* d = pool_.FindMessageTypeByName(name);
        return d;
    }

private:
    void BuildWkt() {
        FileDescriptorProto fdp;
        fdp.set_name("google/protobuf/timestamp.proto");
        fdp.set_package("google.protobuf");
        fdp.set_syntax("proto3");
        auto* ts = fdp.add_message_type();
        ts->set_name("Timestamp");
        AddField(ts, "seconds", 1, FieldDescriptorProto::TYPE_INT64);
        AddField(ts, "nanos", 2, FieldDescriptorProto::TYPE_INT32);
        pool_.BuildFile(fdp);

        FileDescriptorProto dfp;
        dfp.set_name("google/protobuf/duration.proto");
        dfp.set_package("google.protobuf");
        dfp.set_syntax("proto3");
        auto* dur = dfp.add_message_type();
        dur->set_name("Duration");
        AddField(dur, "seconds", 1, FieldDescriptorProto::TYPE_INT64);
        AddField(dur, "nanos", 2, FieldDescriptorProto::TYPE_INT32);
        pool_.BuildFile(dfp);
    }

    void BuildProto2() {
        FileDescriptorProto fdp;
        fdp.set_name("proto2fix.proto");
        fdp.set_package("unit");
        // proto2 (default) — an explicit optional scalar is nullable.
        auto* msg = fdp.add_message_type();
        msg->set_name("Proto2Optional");
        AddField(msg, "maybe", 1, FieldDescriptorProto::TYPE_INT32,
                 FieldDescriptorProto::LABEL_OPTIONAL);
        pool_.BuildFile(fdp);
    }

    void BuildMain() {
        FileDescriptorProto fdp;
        fdp.set_name("fixtures.proto");
        fdp.set_package("unit");
        fdp.set_syntax("proto3");
        fdp.add_dependency("google/protobuf/timestamp.proto");
        fdp.add_dependency("google/protobuf/duration.proto");

        // AllScalars — every supported scalar.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("AllScalars");
            AddField(msg, "f_bool", 1, FieldDescriptorProto::TYPE_BOOL);
            AddField(msg, "f_int32", 2, FieldDescriptorProto::TYPE_INT32);
            AddField(msg, "f_int64", 3, FieldDescriptorProto::TYPE_INT64);
            AddField(msg, "f_uint32", 4, FieldDescriptorProto::TYPE_UINT32);
            AddField(msg, "f_uint64", 5, FieldDescriptorProto::TYPE_UINT64);
            AddField(msg, "f_float", 6, FieldDescriptorProto::TYPE_FLOAT);
            AddField(msg, "f_double", 7, FieldDescriptorProto::TYPE_DOUBLE);
            AddField(msg, "f_string", 8, FieldDescriptorProto::TYPE_STRING);
            AddField(msg, "f_bytes", 9, FieldDescriptorProto::TYPE_BYTES);
        }

        // Helper struct reused by nested/repeated/map-struct fixtures.
        {
            auto* inner = fdp.add_message_type();
            inner->set_name("Inner");
            AddField(inner, "value", 1, FieldDescriptorProto::TYPE_STRING);
        }

        // WKT timestamp / duration.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("TimestampHolder");
            AddField(msg, "stamp", 1, FieldDescriptorProto::TYPE_MESSAGE)
                ->set_type_name(".google.protobuf.Timestamp");
        }
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("DurationHolder");
            AddField(msg, "dur", 1, FieldDescriptorProto::TYPE_MESSAGE)
                ->set_type_name(".google.protobuf.Duration");
        }

        // Repeated scalar -> list<scalar>.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("RepeatedScalarHolder");
            AddField(msg, "values", 1, FieldDescriptorProto::TYPE_INT32,
                     FieldDescriptorProto::LABEL_REPEATED);
        }

        // Singular nested struct.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("NestedStructHolder");
            AddField(msg, "inner", 2, FieldDescriptorProto::TYPE_MESSAGE)
                ->set_type_name(".unit.Inner");
        }

        // Repeated struct -> list<struct>.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("RepeatedStructHolder");
            AddField(msg, "items", 1, FieldDescriptorProto::TYPE_MESSAGE,
                     FieldDescriptorProto::LABEL_REPEATED)
                ->set_type_name(".unit.Inner");
        }

        // map<string,int64> -> arrow map with scalar value.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("MapScalarHolder");
            AddMapEntry(msg, msg, "tags", 1, "TagsEntry", FieldDescriptorProto::TYPE_STRING,
                        FieldDescriptorProto::TYPE_INT64);
        }

        // map<string,Inner> -> arrow map with struct value.
        {
            auto* msg = fdp.add_message_type();
            msg->set_name("MapStructHolder");
            AddMapEntry(msg, msg, "things", 1, "ThingsEntry", FieldDescriptorProto::TYPE_STRING,
                        FieldDescriptorProto::TYPE_MESSAGE, ".unit.Inner");
        }

        // Enum lowered to int32.
        {
            auto* en = fdp.add_enum_type();
            en->set_name("Color");
            auto* v0 = en->add_value();
            v0->set_name("COLOR_UNKNOWN");
            v0->set_number(0);
            auto* v1 = en->add_value();
            v1->set_name("COLOR_RED");
            v1->set_number(1);

            auto* msg = fdp.add_message_type();
            msg->set_name("EnumHolder");
            AddField(msg, "c", 1, FieldDescriptorProto::TYPE_ENUM)->set_type_name(".unit.Color");
        }

        pool_.BuildFile(fdp);
    }

    DescriptorPool pool_;
};

// The fixtures and the golden file each is compared against.
struct Case {
    std::string message;  // fully-qualified message name in the pool
    std::string golden;   // golden .ipc file basename
};

const std::vector<Case>& Cases() {
    static const std::vector<Case> kCases = {
        {"unit.AllScalars", "AllScalars.ipc"},
        {"unit.Proto2Optional", "Proto2Optional.ipc"},
        {"unit.TimestampHolder", "TimestampHolder.ipc"},
        {"unit.DurationHolder", "DurationHolder.ipc"},
        {"unit.RepeatedScalarHolder", "RepeatedScalarHolder.ipc"},
        {"unit.NestedStructHolder", "NestedStructHolder.ipc"},
        {"unit.RepeatedStructHolder", "RepeatedStructHolder.ipc"},
        {"unit.MapScalarHolder", "MapScalarHolder.ipc"},
        {"unit.MapStructHolder", "MapStructHolder.ipc"},
        {"unit.EnumHolder", "EnumHolder.ipc"},
    };
    return kCases;
}

std::filesystem::path GoldenDir() { return std::filesystem::path(SCHEMA_GOLDEN_DIR); }

std::vector<uint8_t> ReadFileBytes(const std::filesystem::path& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return {};
    return std::vector<uint8_t>((std::istreambuf_iterator<char>(in)),
                                std::istreambuf_iterator<char>());
}

// Serialize the schema the IR-driven nanoarrow sink builds for `msg`.
std::vector<uint8_t> IrSchemaIpc(const Descriptor* msg) {
    nanoarrow::UniqueSchema schema;
    cb::BuildMessageSchemaIntoFromIr(msg, schema.get());
    return fletcher::SerializeSchemaIpc(schema.get());
}

// ===========================================================================
// Recording decorator: captures the ordered stream of sink operations the
// visitor issues, with canonical (first-seen order) node ids so the two sinks'
// traces are directly comparable.
// ===========================================================================

class RecordingSink : public cb::SchemaSink {
public:
    explicit RecordingSink(cb::SchemaSink& inner) : inner_(inner) {}

    std::vector<std::string> log;

    cb::SchemaRef Root() override {
        cb::SchemaRef r = inner_.Root();
        log.push_back("Root=" + Id(r));
        return r;
    }
    void InitRootStruct(cb::SchemaRef root, int64_t n) override {
        log.push_back("InitRootStruct(" + Id(root) + "," + std::to_string(n) + ")");
        inner_.InitRootStruct(root, n);
    }
    cb::SchemaRef Child(cb::SchemaRef p, int i) override {
        cb::SchemaRef c = inner_.Child(p, i);
        log.push_back("Child(" + Id(p) + "," + std::to_string(i) + ")=" + Id(c));
        return c;
    }
    void SetTypeScalar(cb::SchemaRef s, ArrowType t) override {
        log.push_back("SetTypeScalar(" + Id(s) + "," + std::to_string(static_cast<int>(t)) + ")");
        inner_.SetTypeScalar(s, t);
    }
    void SetTypeList(cb::SchemaRef s) override {
        log.push_back("SetTypeList(" + Id(s) + ")");
        inner_.SetTypeList(s);
    }
    void SetTypeMap(cb::SchemaRef s) override {
        log.push_back("SetTypeMap(" + Id(s) + ")");
        inner_.SetTypeMap(s);
    }
    void SetTypeDateTime(cb::SchemaRef s, ArrowType t, ArrowTimeUnit u, const char* tz) override {
        log.push_back("SetTypeDateTime(" + Id(s) + "," + std::to_string(static_cast<int>(t)) + "," +
                      std::to_string(static_cast<int>(u)) + "," + (tz ? tz : "null") + ")");
        inner_.SetTypeDateTime(s, t, u, tz);
    }
    void SetName(cb::SchemaRef s, std::string_view n) override {
        log.push_back("SetName(" + Id(s) + "," + std::string(n) + ")");
        inner_.SetName(s, n);
    }
    void SetNullable(cb::SchemaRef s, bool b) override {
        log.push_back("SetNullable(" + Id(s) + "," + (b ? "1" : "0") + ")");
        inner_.SetNullable(s, b);
    }
    void SetMetadata(cb::SchemaRef s,
                     const std::vector<std::pair<std::string, std::string>>& p) override {
        std::string m = "SetMetadata(" + Id(s);
        for (const auto& kv : p) m += "," + kv.first + "=" + kv.second;
        m += ")";
        log.push_back(m);
        inner_.SetMetadata(s, p);
    }
    void DeepCopyMessageStruct(const Descriptor* d, cb::SchemaRef dst) override {
        log.push_back("DeepCopy(" + std::string(d->full_name()) + "," + Id(dst) + ")");
        inner_.DeepCopyMessageStruct(d, dst);
    }

private:
    std::string Id(cb::SchemaRef r) {
        auto it = ids_.find(r);
        if (it != ids_.end()) return std::to_string(it->second);
        int id = next_++;
        ids_[r] = id;
        return std::to_string(id);
    }

    cb::SchemaSink& inner_;
    std::map<cb::SchemaRef, int> ids_;
    int next_ = 0;
};

std::vector<std::string> TraceCpp(const Descriptor* msg) {
    std::ostringstream sink_out;
    cb::CppSchemaSink cpp(sink_out, "    ", msg->file());
    RecordingSink rec(cpp);
    cb::SchemaVisitor(msg, msg->file(), rec).Visit();
    return rec.log;
}

std::vector<std::string> TraceNano(const Descriptor* msg) {
    nanoarrow::UniqueSchema schema;
    cb::NanoarrowSchemaSink nano(schema.get());
    RecordingSink rec(nano);
    cb::SchemaVisitor(msg, msg->file(), rec).Visit();
    return rec.log;
}

}  // namespace

// ===========================================================================
// Forcing test.
// ===========================================================================

TEST(SchemaVisitor, CppAndIpcByteIdentical) {
    Fixtures fx;

    for (const auto& c : Cases()) {
        SCOPED_TRACE(c.message);
        const Descriptor* msg = fx.Get(c.message);
        ASSERT_NE(msg, nullptr) << "fixture message not found: " << c.message;

        // (1) Anti-drift: the IR-driven nanoarrow schema is byte-identical to the
        // committed golden captured from today's emitter.
        const std::vector<uint8_t> golden = ReadFileBytes(GoldenDir() / c.golden);
        ASSERT_FALSE(golden.empty())
            << "missing golden " << c.golden
            << " (regenerate with FLETCHER_CAPTURE_GOLDENS=1)";
        const std::vector<uint8_t> actual = IrSchemaIpc(msg);
        EXPECT_EQ(actual, golden) << "IR schema drifted from golden for " << c.message;

        // (2) One visitor, both sinks agree: the C++ source sink and the nanoarrow
        // sink receive an identical ordered stream of operations.
        EXPECT_EQ(TraceCpp(msg), TraceNano(msg))
            << "C++ source and in-process schema paths diverged for " << c.message;
    }
}

// Golden regeneration helper. Inert unless FLETCHER_CAPTURE_GOLDENS is set; when
// set it writes each golden from the LEGACY in-process BuildMessageSchema (the
// pre-migration ground truth) into SCHEMA_GOLDEN_DIR and then skips.
TEST(SchemaVisitor, CaptureGoldens) {
    const char* capture = std::getenv("FLETCHER_CAPTURE_GOLDENS");
    if (!capture || std::string(capture).empty()) {
        GTEST_SKIP() << "set FLETCHER_CAPTURE_GOLDENS=1 to (re)capture goldens";
    }

    Fixtures fx;
    std::filesystem::create_directories(GoldenDir());
    for (const auto& c : Cases()) {
        const Descriptor* msg = fx.Get(c.message);
        ASSERT_NE(msg, nullptr) << c.message;
        nanoarrow::UniqueSchema schema = fletcher::BuildMessageSchema(msg);
        const std::vector<uint8_t> bytes = fletcher::SerializeSchemaIpc(schema.get());
        const std::filesystem::path path = GoldenDir() / c.golden;
        std::ofstream out(path, std::ios::binary);
        ASSERT_TRUE(out) << "cannot write " << path;
        out.write(reinterpret_cast<const char*>(bytes.data()),
                  static_cast<std::streamsize>(bytes.size()));
    }
    SUCCEED() << "captured " << Cases().size() << " goldens into " << GoldenDir().string();
}
