// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 The Fletcher Authors
//
// The C# half of the binding ABI conformance suite.
//
// ── The question this answers, and the one it cannot ────────────────────────
// Every Fletcher binding calls ONE codec, so "do C# and C++ encode the same
// bytes?" is not a question — there is only one encoder, and asking it would
// certify nothing. The open question is one layer up, and it is a real one:
//
//   Two INDEPENDENT Arrow implementations build the same logical batch. Do they
//   hand the codec the same thing?
//
// Arrow C++ built these fixtures and wrote them out as IPC. `Apache.Arrow`
// rebuilds its own arrays from that IPC, lays out its own buffers, and exports
// them across the C Data Interface. Offsets, validity bitmaps, child ordering,
// buffer padding, the empty-vs-null distinction — the two libraries agree on all
// of it, or the codec reads the difference straight onto the wire. That failure
// does not crash: it is a subscriber decoding a publisher's row into the wrong
// values, which is the most expensive kind of wrong available here.
//
// So the assertion is byte identity against what C++ produced, over the corpus
// D-BIND-35 already ruled the right one, reused rather than rewritten
// (D-BIND-40).
//
// ── What is deliberately NOT asserted ───────────────────────────────────────
// That the bytes are "correct". Nothing here is a second implementation of the
// wire format, and one cannot be written in C# — D-BIND-1 forbids it. Correctness
// is `NanoarrowCodec.ByteIdenticalToArrowBridge`'s job, against arrow-bridge, in
// C++. This suite asks only whether the binding is a faithful path to that codec.
using System;
using System.Buffers;
using System.Collections.Generic;
using System.IO;

using Apache.Arrow;
using Apache.Arrow.Ipc;

using Xunit;

namespace Eiva.Fletcher.Conformance;

public sealed class CorpusConformanceTests
{
    /// <summary>Where `emit_corpus` wrote the corpus.</summary>
    /// <remarks>
    /// An environment variable rather than a committed path: the corpus is
    /// REGENERATED by the C++ emitter on every run, so that it cannot go stale
    /// against a codec change. A committed corpus would be a golden that the thing
    /// it checks is free to drift away from.
    /// </remarks>
    private static string CorpusDirectory =>
        Environment.GetEnvironmentVariable("FLETCHER_CORPUS_DIR")
        ?? throw new InvalidOperationException(
            "FLETCHER_CORPUS_DIR is not set. This suite runs against the corpus emit_corpus " +
            "writes; run that first and point this at its output directory.");

    /// <summary>One case per fixture, DISCOVERED from the emitter's manifest.</summary>
    /// <remarks>
    /// Read rather than listed, so a fixture added to `codec_corpus.hpp` is
    /// exercised here without anyone remembering to add it. A hand-written list is
    /// how a corpus grows a scenario that nothing on the other side consumes.
    /// </remarks>
    public static TheoryData<string, int, int> Fixtures
    {
        get
        {
            var data = new TheoryData<string, int, int>();
            foreach (string line in File.ReadAllLines(Path.Combine(CorpusDirectory, "manifest.txt")))
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                string[] parts = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                data.Add(parts[0], int.Parse(parts[1]), int.Parse(parts[2]));
            }

            return data;
        }
    }

    /// <summary>
    /// C#'s export of the batch encodes to the bytes C++'s export encoded to.
    /// </summary>
    /// <remarks>
    /// The forcing property of this suite. Both sides run the same codec, so a
    /// difference here is a difference between the two Arrow implementations'
    /// idea of the same batch — which is precisely what a binding is exposed to
    /// and what nothing else in the tree checks.
    /// </remarks>
    [Theory]
    [MemberData(nameof(Fixtures))]
    public void ManagedArrowEncodesTheBytesNativeArrowDid(string name, int rows, int byteCount)
    {
        RecordBatch batch = ReadBatch(name);
        byte[] expected = File.ReadAllBytes(Path.Combine(CorpusDirectory, name + ".rows.bin"));

        Assert.Equal(rows, batch.Length);
        Assert.Equal(byteCount, expected.Length);

        using var codec = new FletcherCodec(batch.Schema);
        var output = new ArrayBufferWriter<byte>();
        using (BoundRows bound = codec.Bind(batch))
        {
            for (int row = 0; row < bound.Length; ++row)
            {
                codec.Encode(bound, row, output);
            }
        }

        Assert.Equal(expected, output.WrittenSpan.ToArray());
    }

    /// <summary>The bytes C++ produced decode, through the binding, to the values.</summary>
    /// <remarks>
    /// The other direction, and it is not implied by the one above: an encoder and
    /// a decoder that agreed on a wrong layout would still round-trip. Here the
    /// BYTES come from C++ and the VALUES come from C++, and only the decode is
    /// the binding's — so a managed importer that mislaid a column or a null has
    /// nowhere to hide.
    /// </remarks>
    [Theory]
    [MemberData(nameof(Fixtures))]
    public void NativeBytesDecodeToNativeValuesThroughTheBinding(string name, int rows, int byteCount)
    {
        RecordBatch expected = ReadBatch(name);
        byte[] encoded = File.ReadAllBytes(Path.Combine(CorpusDirectory, name + ".rows.bin"));
        Assert.Equal(byteCount, encoded.Length);

        using var codec = new FletcherCodec(expected.Schema);
        using RecordBatch decoded = codec.DecodeBatch(encoded, rows);

        Assert.Equal(rows, decoded.Length);
        Assert.Equal(expected.ColumnCount, decoded.ColumnCount);

        for (int column = 0; column < expected.ColumnCount; ++column)
        {
            IArrowArray left = expected.Column(column);
            IArrowArray right = decoded.Column(column);

            Assert.Equal(left.Length, right.Length);
            Assert.Equal(left.NullCount, right.NullCount);

            // Null POSITIONS, not just the count: two columns can share a null
            // count and disagree about which rows are null, and the wire format's
            // whole framing is built on the bitfield that says which.
            for (int row = 0; row < left.Length; ++row)
            {
                Assert.Equal(left.IsNull(row), right.IsNull(row));
            }
        }
    }

    /// <summary>The corpus is not empty, and it is the corpus the emitter wrote.</summary>
    /// <remarks>
    /// The vacuity guard, and this suite needs one more than most: both theories
    /// above are driven by a file, so an emitter that wrote an empty manifest — or
    /// a CI step that ran the tests before the emitter — would produce a theory
    /// with no cases, and a theory with no cases passes.
    /// </remarks>
    [Fact]
    public void TheCorpusWasEmitted()
    {
        Assert.True(
            Directory.Exists(CorpusDirectory),
            $"no corpus at {CorpusDirectory}; emit_corpus has not run");

        string[] manifest = File.ReadAllLines(Path.Combine(CorpusDirectory, "manifest.txt"));
        Assert.NotEmpty(manifest);

        foreach (string line in manifest)
        {
            string name = line.Split(' ')[0];
            Assert.True(File.Exists(Path.Combine(CorpusDirectory, name + ".arrows")));
            Assert.True(File.Exists(Path.Combine(CorpusDirectory, name + ".rows.bin")));
        }
    }

    /// <summary>Rebuild a fixture's batch from the Arrow IPC C++ wrote.</summary>
    private static RecordBatch ReadBatch(string name)
    {
        using FileStream file = File.OpenRead(Path.Combine(CorpusDirectory, name + ".arrows"));
        using var reader = new ArrowStreamReader(file);

        RecordBatch? batch = reader.ReadNextRecordBatch();
        Assert.NotNull(batch);
        return batch!;
    }
}
