// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 The Fletcher Authors
//
// BIND-3c: the refill path, and the rule that nothing may escape a thunk.
//
// The encoder uses the window as RANDOM ACCESS, not as a stream: it back-patches
// length prefixes and null bitfields at offsets below the cursor. So a refill
// that failed to carry those bytes across would not crash and would not throw -
// it would produce a row that still parses, as different values. That is the
// failure this file is built around, and it is why the comparison below is
// against bytes produced WITHOUT a refill rather than against a golden: a golden
// would have to be regenerated by the same code it is meant to check.
using System;
using System.Buffers;

using Apache.Arrow;

using Xunit;

namespace Eiva.Fletcher.Tests;

public sealed class WriteWindowTests
{
    /// <summary>What <c>GrowingWindow</c> asks the caller's writer for first.</summary>
    /// <remarks>
    /// Read from the implementation rather than restated, so the fixtures below
    /// can be sized ABOVE it on purpose and stay that way. A row smaller than this
    /// never refills, and a test that happened to use one would pass while
    /// exercising nothing.
    /// </remarks>
    private static int FirstWindowHint => GrowingWindow.FirstWindowHint;

    /// <summary>A refilled encode produces the bytes an unrefilled one does.</summary>
    /// <remarks>
    /// Both sides run the same encoder over the same row; the only difference is
    /// how much room it had to start with. A writer pre-sized past the whole row
    /// never refills, and the default one refills several times — so any byte the
    /// refill moved, dropped or failed to back-patch shows up as a difference.
    /// </remarks>
    [Theory]
    [InlineData(1_000)]
    [InlineData(10_000)]
    [InlineData(100_000)]
    public void ARefilledEncodeProducesTheSameBytesAsOneThatNeverRefilled(int stringLength)
    {
        RecordBatch batch = CodecFixtures.Large(stringLength);
        using var codec = new FletcherCodec(batch.Schema);
        using BoundRows rows = codec.Bind(batch);

        // Pre-sized well past the row: `GetMemory` hands back everything free, so
        // the encode never asks for more.
        var unrefilled = new ArrayBufferWriter<byte>(stringLength * 4);
        codec.Encode(rows, 0, unrefilled);

        var refilled = new ArrayBufferWriter<byte>();
        codec.Encode(rows, 0, refilled);

        // Vacuity guard, by construction rather than by a counter: the encode
        // starts with at most what a 512-byte hint returns, and this row is bigger
        // than that, so at least one refill happened.
        Assert.True(
            unrefilled.WrittenCount > FirstWindowHint,
            $"the row encoded to {unrefilled.WrittenCount} bytes, which fits the first window, so " +
            "this case never refilled and asserts nothing");

        Assert.Equal(unrefilled.WrittenSpan.ToArray(), refilled.WrittenSpan.ToArray());
    }

    /// <summary>A refilled row still decodes to the values it was built from.</summary>
    /// <remarks>
    /// The byte comparison above would also hold if BOTH sides were wrong in the
    /// same way — they run the same encoder. This closes that by leaving the
    /// encoder entirely: the bytes go back through the decoder and the string
    /// comes out whole.
    /// </remarks>
    [Fact]
    public void ARefilledRowSurvivesTheRoundTrip()
    {
        const int Length = 50_000;
        RecordBatch batch = CodecFixtures.Large(Length);
        using var codec = new FletcherCodec(batch.Schema);

        var output = new ArrayBufferWriter<byte>();
        using (BoundRows rows = codec.Bind(batch))
        {
            codec.Encode(rows, 0, output);
        }

        using RecordBatch decoded = codec.Decode(output.WrittenSpan);

        var expected = (StringArray)batch.Column(1);
        var actual = (StringArray)decoded.Column(1);
        Assert.Equal(1, decoded.Length);
        Assert.Equal(expected.GetString(0), actual.GetString(0));
    }

    /// <summary>A row that fits the first window costs no refill and still lands.</summary>
    /// <remarks>
    /// The other half of the design: growth belongs to the window, and a row small
    /// enough is written straight into the caller's own memory. The observable
    /// difference is only that the bytes are right, so this exists to keep the
    /// common path under test rather than to prove the absence of a copy.
    /// </remarks>
    [Fact]
    public void ASmallRowIsWrittenStraightIntoTheCallersMemory()
    {
        RecordBatch batch = CodecFixtures.Scalar();
        using var codec = new FletcherCodec(batch.Schema);
        using BoundRows rows = codec.Bind(batch);

        var output = new ArrayBufferWriter<byte>();
        codec.Encode(rows, 0, output);

        Assert.InRange(output.WrittenCount, 1, FirstWindowHint);

        using RecordBatch decoded = codec.Decode(output.WrittenSpan);
        Assert.Equal(7, ((Int32Array)decoded.Column(0)).GetValue(0));
    }

    /// <summary>Rows appended to one writer do not run into each other.</summary>
    /// <remarks>
    /// Each encode advances the writer by exactly what it wrote, so N rows into
    /// one writer is the same buffer <c>DecodeBatch</c> expects — the shape a
    /// caller batching for a write-ahead log actually produces.
    /// </remarks>
    [Fact]
    public void RowsAccumulateInOneWriter()
    {
        RecordBatch batch = CodecFixtures.Composite();
        using var codec = new FletcherCodec(batch.Schema);
        using BoundRows rows = codec.Bind(batch);

        var output = new ArrayBufferWriter<byte>();
        int previous = 0;
        for (int row = 0; row < rows.Length; ++row)
        {
            codec.Encode(rows, row, output);
            Assert.True(output.WrittenCount > previous, $"row {row} advanced the writer by nothing");
            previous = output.WrittenCount;
        }

        using RecordBatch decoded = codec.DecodeBatch(output.WrittenSpan, rows.Length);
        Assert.Equal(batch.Length, decoded.Length);
    }

    /// <summary>
    /// A refill that throws does not cross the boundary, and the original
    /// exception is what the caller sees.
    /// </summary>
    /// <remarks>
    /// N-1 and D-BIND-19 rule 3, together. A managed exception escaping an
    /// <c>[UnmanagedCallersOnly]</c> method is a FAIL-FAST — the runtime cannot
    /// unwind through a C frame — so the thunk catches it, the shim turns the
    /// refusal into a failed encode, and the throw site rethrows THAT exception
    /// rather than a <c>FletcherException</c> wrapping it. A caller's own
    /// contract is not rewritten by having crossed a boundary.
    ///
    /// That this test runs at all is half the assertion: a thunk that let the
    /// exception through would take the test process with it.
    /// </remarks>
    [Fact]
    public void AThrowingRefillComesBackAsItselfAndPublishesNothing()
    {
        RecordBatch batch = CodecFixtures.Large(10_000);
        using var codec = new FletcherCodec(batch.Schema);
        using BoundRows rows = codec.Bind(batch);

        var fault = new InvalidOperationException("the refill declined");
        codec.RefillFaultForTest = fault;

        var output = new ArrayBufferWriter<byte>();
        InvalidOperationException thrown =
            Assert.Throws<InvalidOperationException>(() => codec.Encode(rows, 0, output));

        Assert.Same(fault, thrown);

        // A FAILED ENCODE ADVANCES NOTHING. The writer is left as it was found, so
        // a caller batching rows into one buffer has no half-row in it.
        Assert.Equal(0, output.WrittenCount);
    }

    /// <summary>The codec survives a refusal: the next encode is unaffected.</summary>
    /// <remarks>
    /// The failure path unpins a buffer, frees a GC handle and leaves a captured
    /// exception behind. If any of that leaked into the codec rather than into the
    /// per-encode window, the following encode would fail too — or worse, succeed
    /// with the previous row's state.
    /// </remarks>
    [Fact]
    public void ARefusedEncodeLeavesTheCodecUsable()
    {
        RecordBatch batch = CodecFixtures.Large(10_000);
        using var codec = new FletcherCodec(batch.Schema);
        using BoundRows rows = codec.Bind(batch);

        codec.RefillFaultForTest = new InvalidOperationException("the refill declined");
        Assert.Throws<InvalidOperationException>(
            () => codec.Encode(rows, 0, new ArrayBufferWriter<byte>()));

        codec.RefillFaultForTest = null;

        var output = new ArrayBufferWriter<byte>();
        codec.Encode(rows, 0, output);

        using RecordBatch decoded = codec.Decode(output.WrittenSpan);
        Assert.Equal(
            ((StringArray)batch.Column(1)).GetString(0),
            ((StringArray)decoded.Column(1)).GetString(0));
    }
}
