/**
 * eiva-fletcher-codec — public API.
 *
 * Wire format primitives, schema descriptors, and codec for the Fletcher
 * positional row format. Used both by hand-written clients (e.g.
 * gateway-client) and by TypeScript code generated by protoc-gen-fletcher.
 */

// Wire format
export { WireTypeId, scalarByteSize } from './wire-types.js';

// Schema descriptors
export type { SchemaDescriptor, FieldDescriptor } from './schema-descriptor.js';

// Codec
export { encodePositional } from './positional-encoder.js';
export { decodePositional } from './positional-decoder.js';

// Backends
export type { DecoderBackend } from './object-backend.js';
export { ObjectBackend } from './object-backend.js';
export { ArrowBackend } from './arrow-backend.js';
