name: Lint GitHub Actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    paths:
      - ".github/**"

jobs:
  actionlint:
    runs-on:
      group: ubuntu_24.04_x64
    steps:
      - name: Checkout .github folder
        uses: actions/checkout@v6

      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
