name: Lint GitHub Actions
on:
  pull_request:
    paths:
      - ".github/**"

jobs:
  actionlint:
    runs-on:
      group: ubuntu_24.04_x64
    steps:
      - name: Checkout .github folder
        uses: actions/checkout@v6

      - name: Check workflow files
        uses: docker://rhysd/actionlint:v1.7.12
        with:
          args: -color
