name: fletcher-gateway-client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "gateway-client-ts/**"
      - ".github/workflows/fletcher-gateway-client.yml"

jobs:
  build-and-test:
    runs-on:
      group: ubuntu_24.04_x64
    defaults:
      run:
        working-directory: gateway-client-ts
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            gateway-client-ts
            .github/workflows

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.15.0
          cache: npm
          cache-dependency-path: gateway-client-ts/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build TS
        run: npm run build:ts

      - name: Test
        run: npm test
